import {createContext,useContext,useRef,useState,useEffect,type ReactNode} from 'react'
import {Play,Pause,SkipBack,SkipForward,X,Volume2} from 'lucide-react'
import {api,time,episodeTitle} from './api'
import type {Episode} from './types'
type AudioState={episode:Episode|null;position:number;playing:boolean;play:(e:Episode,at?:number)=>void;seek:(n:number)=>void;toggle:()=>void}
const AudioContext=createContext<AudioState>(null!)
export const useAudio=()=>useContext(AudioContext)
export function AudioProvider({children,onError}:{children:ReactNode;onError:(e:string)=>void}){
 const [episode,setEpisode]=useState<Episode|null>(null),[position,setPosition]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1)
 const audio=useRef<HTMLAudioElement>(null),pending=useRef<number|null>(null),autoplay=useRef(false),lastSave=useRef(0),episodeRef=useRef<Episode|null>(null)
 function save(){const e=episodeRef.current;if(e&&audio.current)void api(`/episodes/${e.id}/position`,'PUT',{position:audio.current.currentTime}).catch(err=>onError(err.message))}
 function play(e:Episode,at?:number){
   if(!e.has_audio&&!e.audio){onError('Audio has not been imported for this episode yet.');return}
   if(episodeRef.current?.id===e.id){if(at!==undefined)audio.current!.currentTime=at;void audio.current?.play().catch(()=>onError('Press play to start audio.'));return}
   if(episodeRef.current)save();pending.current=at??e.position??0;autoplay.current=true;episodeRef.current=e;setEpisode(e);setPosition(pending.current);lastSave.current=0
 }
 function seek(n:number){if(audio.current)audio.current.currentTime=Math.max(0,Math.min(n,audio.current.duration||episode?.duration||0))}
 function toggle(){if(!audio.current)return;if(playing)audio.current.pause();else void audio.current.play().catch(()=>onError('Could not play audio. Please try again.'))}
 useEffect(()=>{const hide=()=>save();window.addEventListener('pagehide',hide);return()=>window.removeEventListener('pagehide',hide)},[])
 return <AudioContext.Provider value={{episode,position,playing,play,seek,toggle}}>{children}<audio ref={audio} src={episode?`/api/episodes/${episode.id}/audio`:undefined} preload="metadata" onLoadedMetadata={()=>{if(audio.current){audio.current.currentTime=pending.current??0;audio.current.playbackRate=speed;pending.current=null;if(autoplay.current){autoplay.current=false;void audio.current.play().catch(()=>onError('Press play to start audio.'))}}}} onTimeUpdate={()=>{const value=audio.current?.currentTime||0;setPosition(value);if(Date.now()-lastSave.current>15000){lastSave.current=Date.now();save()}}} onPlay={()=>setPlaying(true)} onPause={()=>{setPlaying(false);save()}} onEnded={()=>{setPlaying(false);save()}} onError={()=>episode&&onError('Audio could not load. Check your connection and try again.')}/>{episode&&<section className="player" aria-label="Episode audio player"><div className="player-name"><span className="eyebrow">{episode.day?`DAY ${episode.day}`:'SUPPLEMENTARY EPISODE'}</span><strong>{episodeTitle(episode.title)}</strong></div><div className="player-buttons"><button aria-label="Back 15 seconds" onClick={()=>seek(position-15)}><SkipBack size={18}/><small>15</small></button><button className="play-round" aria-label={playing?'Pause':'Play'} onClick={toggle}>{playing?<Pause size={20}/>:<Play size={20}/>}</button><button aria-label="Forward 15 seconds" onClick={()=>seek(position+15)}><SkipForward size={18}/><small>15</small></button></div><div className="seek"><input aria-label="Audio position" type="range" min="0" max={episode.duration||1} step="0.1" value={Math.min(position,episode.duration||1)} onChange={e=>seek(Number(e.target.value))}/><span>{time(position)} / {time(episode.duration)}</span></div><select aria-label="Playback speed" value={speed} onChange={e=>{const rate=Number(e.target.value);setSpeed(rate);if(audio.current)audio.current.playbackRate=rate}}>{[.75,1,1.25,1.5,1.75,2].map(n=><option key={n} value={n}>{n}×</option>)}</select><label className="volume"><Volume2 size={17}/><input type="range" min="0" max="1" step=".05" defaultValue="1" aria-label="Volume" onChange={e=>{if(audio.current)audio.current.volume=Number(e.target.value)}}/></label><button aria-label="Close player" onClick={()=>{audio.current?.pause();save();episodeRef.current=null;setEpisode(null)}}><X size={18}/></button></section>}</AudioContext.Provider>
}
