# Generated by Django 5.2.17 on 2026-09-19 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                ("number", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("readings", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("color", models.CharField(max_length=7)),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("address", models.GenericIPAddressField()),
                ("attempted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guid", models.CharField(max_length=512, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField()),
                ("source_date", models.DateField()),
                ("audio_url", models.URLField(max_length=2000)),
                ("source_url", models.URLField(blank=True, max_length=2000)),
                ("description", models.TextField(blank=True)),
                ("duration", models.FloatField(default=0)),
                ("audio_file", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("error", models.TextField(blank=True)),
                ("transcript", models.JSONField(default=list)),
                ("classification", models.JSONField(default=list)),
                ("edited_commentary", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("outline", models.JSONField(default=list)),
                ("provenance", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episode",
                        to="study.day",
                    ),
                ),
                (
                    "era",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="study.era",
                    ),
                ),
            ],
            options={
                "ordering": ["published_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="day",
            name="era",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="study.era"),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("note", "Note"), ("journal", "Journal")], max_length=12
                    ),
                ),
                ("body", models.TextField()),
                ("audio_time", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study.day",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study.episode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("book", models.CharField(max_length=40)),
                ("chapter", models.PositiveSmallIntegerField()),
                ("number", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                ("paragraph", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["chapter", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "chapter", "number"), name="unique_verse"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="study.day"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "day"), name="unique_day_progress")
                ],
            },
        ),
        migrations.CreateModel(
            name="EpisodeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.FloatField(default=0)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study.episode"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "episode"), name="unique_episode_progress"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_date__gte", "2025-01-01"), ("source_date__lt", "2026-01-01")
                ),
                name="episode_published_in_2025",
            ),
        ),
        migrations.AddConstraint(
            model_name="day",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 365)), name="day_1_to_365"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("day__isnull", False), ("episode__isnull", True)),
                    models.Q(("day__isnull", True), ("episode__isnull", False)),
                    _connector="OR",
                ),
                name="note_exactly_one_target",
            ),
        ),
    ]
