# Generated by Django 5.1 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="key_points",
            field=models.JSONField(default=list),
        ),
    ]
