# Generated by Django 5.2.17 on 2026-09-20 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_episode_key_points"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="note",
            name="shared_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("leaderboard_visible", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "progress_basis",
                    models.CharField(
                        choices=[
                            ("first-completion", "Personal start dates"),
                            ("leaderboard", "Leaderboard start date"),
                            ("january-1", "January 1"),
                        ],
                        default="first-completion",
                        max_length=24,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
