# Generated by Django 5.2.17 on 2026-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0003_note_shared_note_shared_notified_at_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunitySettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("start_date", models.DateField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_community_settings"
                    )
                ],
            },
        ),
    ]
