# Generated by Django 5.2.17 on 2026-09-20 15:38

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0004_communitysettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="StudyWorker",
            fields=[
                ("name", models.CharField(max_length=120, primary_key=True, serialize=False)),
                ("heartbeat_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SearchChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=180, unique=True)),
                ("kind", models.CharField(max_length=20)),
                ("source", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=600)),
                ("text", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("digest", models.CharField(max_length=64)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("leased_until", models.DateTimeField(null=True)),
                ("error", models.CharField(blank=True, max_length=100)),
                (
                    "episode",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="study.episode"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="study.note"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "day",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="study.day"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="study.episode"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("question", models.TextField()),
                ("external_query", models.CharField(blank=True, max_length=500)),
                ("web_enabled", models.BooleanField(default=True)),
                ("status", models.CharField(db_index=True, default="queued", max_length=16)),
                ("answer", models.TextField(blank=True)),
                ("sources", models.JSONField(default=list)),
                ("notices", models.JSONField(default=list)),
                ("stage", models.CharField(default="Waiting for the study worker", max_length=120)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="study.studyconversation",
                    ),
                ),
            ],
        ),
    ]
