# Generated by Django 5.2.17 on 2026-09-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_studyworker_searchchunk_studyconversation_studyturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyturn',
            name='follow_ups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
