# Generated by Django 5.2.17 on 2026-09-21 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_studyturn_follow_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('default_year', models.IntegerField()),
                ('wiki_url', models.URLField(blank=True, max_length=2000)),
                ('category', models.CharField(max_length=80)),
                ('condemned_by_council', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['default_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=36, unique=True)),
                ('file_name', models.CharField(max_length=500)),
                ('append_to_author_name', models.CharField(blank=True, max_length=500)),
                ('year', models.IntegerField(db_index=True)),
                ('book_key', models.CharField(db_index=True, max_length=40)),
                ('location_start', models.PositiveIntegerField()),
                ('location_end', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_title', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentaries', to='study.commentaryauthor')),
            ],
            options={
                'ordering': ['year', 'id'],
                'indexes': [models.Index(fields=['book_key', 'location_start', 'location_end'], name='commentary_passage_idx')],
            },
        ),
    ]
