# Generated by Django 5.2.17 on 2026-09-21 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0008_studyturn_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatechismDay",
            fields=[
                ("number", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("part", models.CharField(max_length=120)),
                ("section", models.CharField(blank=True, max_length=120)),
                ("chapter", models.CharField(blank=True, max_length=120)),
                ("paragraph_start", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("paragraph_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("color", models.CharField(max_length=7)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="CatechismDayProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CatechismParagraph",
            fields=[
                ("number", models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("source_url", models.URLField(max_length=2000)),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="note",
            name="note_exactly_one_target",
        ),
        migrations.AddField(
            model_name="communitysettings",
            name="catechism_start_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="edition",
            field=models.CharField(
                choices=[("bible", "Bible in a Year"), ("catechism", "Catechism in a Year")],
                default="bible",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="bible_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="catechism_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="catechism_progress_basis",
            field=models.CharField(
                choices=[
                    ("first-completion", "Personal start dates"),
                    ("leaderboard", "Leaderboard start date"),
                    ("january-1", "January 1"),
                ],
                default="first-completion",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="studyconversation",
            name="edition",
            field=models.CharField(
                choices=[("bible", "Bible in a Year"), ("catechism", "Catechism in a Year")],
                default="bible",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="catechismday",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1), ("number__lte", 365)),
                name="catechism_day_1_to_365",
            ),
        ),
        migrations.AddConstraint(
            model_name="catechismday",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("paragraph_end__isnull", True), ("paragraph_start__isnull", True)),
                    models.Q(("paragraph_end__isnull", False), ("paragraph_start__isnull", False)),
                    _connector="OR",
                ),
                name="catechism_day_complete_paragraph_range",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="catechism_day",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="episode",
                to="study.catechismday",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="catechism_day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="study.catechismday",
            ),
        ),
        migrations.AddField(
            model_name="studyconversation",
            name="catechism_day",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="study.catechismday"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("catechism_day__isnull", True),
                        ("day__isnull", False),
                        ("episode__isnull", True),
                    ),
                    models.Q(
                        ("catechism_day__isnull", False),
                        ("day__isnull", True),
                        ("episode__isnull", True),
                    ),
                    models.Q(
                        ("catechism_day__isnull", True),
                        ("day__isnull", True),
                        ("episode__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="note_exactly_one_target",
            ),
        ),
        migrations.AddField(
            model_name="catechismdayprogress",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="study.catechismday"
            ),
        ),
        migrations.AddField(
            model_name="catechismdayprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="catechismdayprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "day"), name="unique_catechism_day_progress"
            ),
        ),
    ]
