# Generated by Django 5.2.17 on 2026-09-22 00:59

import datetime

from django.db import migrations, models


def apply_notification_defaults(apps, schema_editor):
    Profile = apps.get_model("study", "Profile")
    untouched_ids = list(
        Profile.objects.filter(
            morning_reminder_enabled=False,
            morning_reminder_time=datetime.time(7, 0),
            evening_reminder_enabled=False,
            evening_reminder_time=datetime.time(20, 0),
            shared_push_notifications=False,
            reminder_condition="never",
            user__push_subscriptions__isnull=True,
        ).values_list("pk", flat=True)
    )
    Profile.objects.exclude(pk__in=untouched_ids).update(notification_setup_completed=True)
    Profile.objects.filter(pk__in=untouched_ids).update(
        morning_reminder_enabled=True,
        morning_reminder_time=datetime.time(8, 0),
        evening_reminder_enabled=True,
        shared_push_notifications=True,
        reminder_condition="incomplete",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_profile_evening_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(apply_notification_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='evening_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='morning_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='morning_reminder_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reminder_condition',
            field=models.CharField(choices=[('incomplete', 'Only when today’s reading is incomplete'), ('always', 'Always'), ('never', 'Never')], default='incomplete', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shared_push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
