# Generated by Django 5.2.17 on 2026-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0015_non_ai_site_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="catechismparagraph",
            name="content",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="catechismparagraph",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
